### PR TITLE
Fix handle double length block

### PR DESCRIPTION
**Pull request by rumickon**

### CODE REVIEW

**Comment by viveleroi** [comment]
What is this fixing? If the conditions within the `switch` statement are not met, the execution continues to the `return null` at the end of the file, so these additions aren't necessary.

**Comment by rumickon** [comment]
1. When block type is WOODEN_DOOR and block.getData() == 0 or 1 we go to `Bed b = (Bed)block.getState().getData();` and get exception.
2. If we have BED_BLOCK and isHeadOfBed == false we go to `findFirstSurroundingBlockOfType(block, block.getType());`

So we can fix it by adding `return null` or `break` to that conditions.

**Comment by viveleroi** [comment]
Let's change them to `break;` statements, that's what should be there anyway, and I shouldn't have returned from within a switch to begin with. Ugh.

**Comment by rumickon** [comment]
https://github.com/prism/elixr/pull/5

**Pull request closed without merging**
